### ISSUE TITLE
Unable to load EH3779, mouse cell line altas

### ISSUE THREAD

**Issue by liu2005678** [rnabioco/clustifyrdatahub#4]
Error: failed to load resource
  name: EH3779
  title: ref_mouse_atlas
  reason: 在为'get'函数选择方法时评估'x'参数出了错: bad restore file magic number (file may be corrupted) -- no data loaded 
In addition: Warning messages:
1: In readChar(con, 5L, useBytes = TRUE) :
  truncating string with embedded nuls
2: file ‘3b4c6edf29e8_3815’ has magic number 'X'
  Use of save versions prior to 2 is deprecated

**Comment by kriemo** [comment]
Thanks for the bug report. Looks like the .rda file is actually a .rds file. I'll fix this in the devel branch, but in the meantime you can access the matrix from github:

``` r
mat <- readRDS(gzcon(url("https://github.com/rnabioco/scRNA-seq-Cell-Ref-Matrix/raw/master/atlas/musMusculus/ref_mouse_atlas.rda")))
mat[1:5, 1:5]
#>               Basal (GSE113049) Ciliated (GSE113049) Club (GSE113049)
#> 0610005C13Rik        0.00000000            0.0000000       0.00000000
#> 0610006L08Rik        0.00000000            0.0000000       0.00000000
#> 0610009B22Rik        0.25201560            0.1865249       0.16681613
#> 0610009O20Rik        0.10757994            0.1971796       0.03376846
#> 0610010F05Rik        0.03996719            0.2684774       0.01664735
#>               Endothelial/Fibroblast (GSE113049)
#> 0610005C13Rik                         0.00000000
#> 0610006L08Rik                         0.00000000
#> 0610009B22Rik                         0.36579922
#> 0610009O20Rik                         0.07482214
#> 0610010F05Rik                         0.06640846
#>               Injured AEC2: Cell Cycle Arrest (GSE113049)
#> 0610005C13Rik                                  0.00000000
#> 0610006L08Rik                                  0.00000000
#> 0610009B22Rik                                  0.40903484
#> 0610009O20Rik                                  0.08527098
#> 0610010F05Rik                                  0.05072260
```

**Comment by liu2005678** [comment]
Thank you very much for the reply 
---- Replied Message ----
| From | Kent ***@***.***> |
| Date | 11/07/2023 22:45 |
| To | rnabioco/clustifyrdatahub ***@***.***> |
| Cc | liu2005678 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [rnabioco/clustifyrdatahub] Unable to load EH3779, mouse cell line altas (Issue #4) |

Thanks for the bug report. Looks like the .rda file is actually a .rds file. I'll fix this in the devel branch, but in the meantime you can access the matrix from github:

mat<- readRDS(gzcon(url("https://github.com/rnabioco/scRNA-seq-Cell-Ref-Matrix/raw/master/atlas/musMusculus/ref_mouse_atlas.rda")))
mat[1:5, 1:5]
#>               Basal (GSE113049) Ciliated (GSE113049) Club (GSE113049)#> 0610005C13Rik        0.00000000            0.0000000       0.00000000#> 0610006L08Rik        0.00000000            0.0000000       0.00000000#> 0610009B22Rik        0.25201560            0.1865249       0.16681613#> 0610009O20Rik        0.10757994            0.1971796       0.03376846#> 0610010F05Rik        0.03996719            0.2684774       0.01664735#>               Endothelial/Fibroblast (GSE113049)#> 0610005C13Rik                         0.00000000#> 0610006L08Rik                         0.00000000#> 0610009B22Rik                         0.36579922#> 0610009O20Rik                         0.07482214#> 0610010F05Rik                         0.06640846#>               Injured AEC2: Cell Cycle Arrest (GSE113049)#> 0610005C13Rik                                  0.00000000#> 0610006L08Rik                                  0.00000000#> 0610009B22Rik                                  0.40903484#> 0610009O20Rik                                  0.08527098#> 0610010F05Rik                                  0.05072260

**Comment by kriemo** [comment]
This issue is now fixed, so you should be able to load the matrix using clustifyrdatahub. 

``` r
library(clustifyrdatahub)
mat <- ref_mouse_atlas()
#> see ?clustifyrdatahub and browseVignettes('clustifyrdatahub') for documentation
#> loading from cache
mat[1:4, 1:4]
#>               Basal (GSE113049) Ciliated (GSE113049) Club (GSE113049)
#> 0610005C13Rik         0.0000000            0.0000000       0.00000000
#> 0610006L08Rik         0.0000000            0.0000000       0.00000000
#> 0610009B22Rik         0.2520156            0.1865249       0.16681613
#> 0610009O20Rik         0.1075799            0.1971796       0.03376846
#>               Endothelial/Fibroblast (GSE113049)
#> 0610005C13Rik                         0.00000000
#> 0610006L08Rik                         0.00000000
#> 0610009B22Rik                         0.36579922
#> 0610009O20Rik                         0.07482214
```

<sup>Created on 2023-11-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
